<?php

include('conexao.php');



$d_tel = sha1('Telefone');
$d_senha = sha1('Senha');
$senha = $_GET['senha'];
$telefone = $_GET['telefone'];
$token = $_GET['token'];

$ver = 'SELECT * FROM usuarios_carrinho WHERE  telefone = '$telefone' AND senha ='$senha'';
$con_v = $conexao->query($ver);
$linh = mysqli_num_rows($con_v);

if ($linh >= 1) {
    
header('location: ../home/');

    
    

}


else{
    var_dump($_POST);
}



?>


<div style='cursor: pointer; bottom: 0; right: 0; display: grid; place-content: center; color: white; position: absolute; width: 2em; height: 2em;'
                                class='bg-warning shadow-lg rounded-circle' onclick='add_prod('<?=$dad['ref']?>','<?=$dad['produto']?>')' >
                                <!-- Generated by IcoMoon.io -->
                                <svg fill='currentColor' version='1.1' xmlns='http://www.w3.org/2000/svg' width='24' height='24'
                                    viewBox='0 0 24 24'>
                                    <title>Adicionar ao carrinho</title>
                                    <path
                                        d='M20.625 11.25h-7.875v-7.875h-1.5v7.875h-7.875v1.5h7.875v7.875h1.5v-7.875h7.875v-1.5z'>
                                    </path>
                                </svg>
                            </div>

                            <div class='load_buy' style='border:6px solid red; height: 2.2rem; width: 2.2rem; border-bottom: 6px solid white; border-radius: 100px;'>
    </div>