<?php
session_start();
include("../func_files/conexao.php");


if (!empty($_SESSION['id'])) {
    
    $nome = $_SESSION['nome'];
    $email = $_SESSION['email'];
    $tel = $_SESSION['tel'];
    $codigo = $_SESSION['codigo'];
    $end = $_SESSION['endereco'];
    $quando = $_SESSION['quando'];


    $p_nome = explode(" ", $nome);
    $primeiro_nome = $p_nome[0];

}

else{
    header("location: ../");
}

?>

<!DOCTYPE html>
<html lang="pt-Br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Compras | Meu Carrinho</title>
    <link rel="shortcut icon" href="../img/logo.jpeg" type="image/x-icon">
    <script src="../jquery.js"></script>
    <link rel="stylesheet" href="../bootstrap/css/bootstrap.css">
    <script src="../bootstrap/js/bootstrap.js"></script>
    <script src="../bootstrap/js/bootstrap.min.js"></script>
    <script src="../owl/dist/owl.carousel.js"></script>
<link rel="stylesheet" href="../owl/dist/assets/owl.carousel.css">
    <script src="../alerts/dist/sweetalert2.js"></script>
    <link rel="stylesheet" href="../alerts/dist/sweetalert2.css">
<link rel="stylesheet" href="../owl/dist/assets/owl.theme.default.css">

</head>
<style>
    .bg-warning{
        background: #FFBF53!important;
    }
    .text-warning{
        color: #c99a49!important;
    }
    body{
        overflow-x: hidden!important;
    }
    .text-sm{
        font-size: 12px;
    }
    .text-xs{
        font-size: 10px;
    }
    .prod .cab .add{
        cursor: pointer!important;
    }

    .dest-am .prod .cab img{
        width: 8rem;
        transition: .3s;
    }

    .prod .cab img{
        transition: .3s;
    }

    .prod:hover .cab img{
        transform: scale(1.06);
        transition: .3s;
    }

    .dest-am .prod{
        border-radius: 15px;
        padding: .6rem;
        background: white!important;
    }
    .logo{
        height: 2em;
        margin-left: .8rem;
    }
    footer div a{
        font-weight: lighter;
    }
    span{
        font-weight: lighter;
    }
    .font-lighter{
        font-weight: lighter;
    }
    .create{
        background: #dc0202;
        color: white;
    }
    .the_menu{
        display: none;
    }

    @media (max-width: 760px) {
        .abs{
            position: absolute;
        }
        .fixo{
            position: fixed;
        }
        .w100{
            width: 100%!important;
        }
    }
    @media (min-width: 760px) {
        .flex-1{
            flex: 1;
        }
    }
</style>
<body>
    <div class="nav bg-warning row px-4 py-3">
        <div class="container ">
           
            <div class="d-flex gap-4 flex-wrap ">
                <div class=" d-grid ">
                    <div class="my-auto position-relative">
                       
        
                        <img src="../img/banner_p.png" alt="" class="navbar-brand logo ">
    
                        <style>
                            .the_menu span{
                                font-size: 13px;
                            }
                        </style>

    
                    </div>
                </div>
                <div class=" flex-1 w100" >
                    <div  style=" display: flex!important;" class="input w-100 py-1 bg-white rounded-pill"><svg class="mx-3" height="2em" width="2em" fill="#ea8e16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 460 512"><path d="M220.6 130.3l-67.2 28.2V43.2L98.7 233.5l54.7-24.2v130.3l67.2-209.3zm-83.2-96.7l-1.3 4.7-15.2 52.9C80.6 106.7 52 145.8 52 191.5c0 52.3 34.3 95.9 83.4 105.5v53.6C57.5 340.1 0 272.4 0 191.6c0-80.5 59.8-147.2 137.4-158zm311.4 447.2c-11.2 11.2-23.1 12.3-28.6 10.5-5.4-1.8-27.1-19.9-60.4-44.4-33.3-24.6-33.6-35.7-43-56.7-9.4-20.9-30.4-42.6-57.5-52.4l-9.7-14.7c-24.7 16.9-53 26.9-81.3 28.7l2.1-6.6 15.9-49.5c46.5-11.9 80.9-54 80.9-104.2 0-54.5-38.4-102.1-96-107.1V32.3C254.4 37.4 320 106.8 320 191.6c0 33.6-11.2 64.7-29 90.4l14.6 9.6c9.8 27.1 31.5 48 52.4 57.4s32.2 9.7 56.8 43c24.6 33.2 42.7 54.9 44.5 60.3s.7 17.3-10.5 28.5zm-9.9-17.9c0-4.4-3.6-8-8-8s-8 3.6-8 8 3.6 8 8 8 8-3.6 8-8z"/></svg><input class="w-75" type="search" style="border: none; outline: none;" placeholder="Pesquisar"></div>
                </div>
                <div title="Seu perfil" style="top: .3%; cursor: pointer; right: 6%" class="my-2 abs my-lg-0 my-md-0 my-xl-0 my-sm-0  d-flex gap-3 ">
                    
                    <div  id="open_menu" style="background: #000; color: white" class="cart px-3 rounded-pill py-2 my-auto"><!-- Generated by IcoMoon.io -->
                        <!-- Generated by IcoMoon.io -->
                        <svg fill="white" version="1.1" xmlns="http://www.w3.org/2000/svg" width="26" height="26" viewBox="0 0 24 24">
                            <title>user</title>
                            <path d="M19.294 16.109l-3.414-2.219 1.287-2.359c0.288-0.519 0.457-1.137 0.458-1.796v-3.735c0-2.9-2.351-5.25-5.25-5.25s-5.25 2.351-5.25 5.25v0 3.735c0.001 0.658 0.17 1.277 0.468 1.815l-0.010-0.019 1.287 2.359-3.414 2.219c-1.033 0.676-1.706 1.828-1.706 3.137 0 0.002 0 0.005 0 0.007v-0 3.997h17.25v-3.997c0-0.002 0-0.005 0-0.007 0-1.309-0.673-2.461-1.692-3.128l-0.014-0.009zM19.5 21.75h-14.25v-2.497c0-0.001 0-0.003 0-0.004 0-0.785 0.404-1.477 1.015-1.877l0.009-0.005 4.578-2.976-1.952-3.578c-0.173-0.311-0.274-0.682-0.275-1.077v-3.735c0-2.071 1.679-3.75 3.75-3.75s3.75 1.679 3.75 3.75v0 3.735c-0 0.395-0.102 0.766-0.281 1.089l0.006-0.012-1.952 3.579 4.578 2.976c0.62 0.406 1.024 1.097 1.024 1.882 0 0.001 0 0.003 0 0.004v-0z"></path>
                            </svg>
    
                       
                    </div>
                    
                        <!--Começo do menu onde tem login e criar conta-->
                        <div class="position-absolute the_menu shadow-lg rounded-3 bg-light py-4 px-3 " style="top: 3.5rem; right: .6rem; border: 1px solid gray;  z-index: 10; width: 20rem;">
                            <h3 class="text-danger"><?=$nome?></h3>
                            <span>Tel: +244 <?=$tel?></span><br>
                            <span>Email: <?=$email?></span><br>
                            <span>End. <?=$end?></span><br>
                            <br>
                            <center><span class="text-warning">Conta activa desde <?=$quando?></span></center>
                            <a href="create_account.php"><button class="btn mt-3 create rounded-5 w-100">Apagar Conta</button></a><br>
                            <center><a href="sair.php">Sair</a></center>
                        </div>
                </div> 
            </div>
        </div><!--Fechamenoto do container dentro da nav-->
    </div><!--Fechamento do cabeçalho da navegação-->



    <br>

    <style>

        .defs .item{
            height: 7rem;
            width: 10rem;
            display: grid;
            place-content: center;
            cursor: pointer;
            margin: 1rem 0;
            transition: .3s;
            box-shadow: 1px 5px 9px rgba(245, 37, 37, 0.582);
        }
        
        .item_, img{
            transition: .3s;
        }

        .item_:hover{
            transform: translateY(-1px);
            transition: .3s;
            box-shadow: 3px 3px 8px rgb(175, 175, 175)!important;
        }
        .item_:hover img{
            transform: translateY(-6px);
            transition: .3s;
        }

        .defs .item span{
            font-size: 30px;
        }

        .defs .item svg{
            fill: rgba(134, 112, 14, 0.74);
        }

        .bg-m{
            background: rgb(255, 248, 210);
        }
        .bg-m div{
            background: rgb(255, 248, 210);
            padding: .8rem;
        }
        
    
    body::-webkit-scrollbar{
        width: 8px;
    }

    body::-webkit-scrollbar-button{
        width: 8px;
        background: red;
        border-radius: 60px;
    }

    body::-webkit-scrollbar-thumb{
        width: 8px;
        background: #FFBF53;
        border-radius: 60px;
    }
    </style>

    <div class="container">
    
        <a href="index.php" class="text-warning">
            <!-- Generated by IcoMoon.io -->
            <svg fill="currentColor" style="font-size: 30px" version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
            <title>Anterior</title>
            <path d="M23.312 11.25h-19.558l4.5-4.5-1.061-1.061-6.31 6.31 6.31 6.31 1.061-1.061-4.5-4.5h19.558v-1.5z"></path>
            </svg>
            </a>
    <h4 class="text-warning">Boa Tarde #BOSS <b><?=$primeiro_nome?>. </b></h4>
    <span class="text-secondary">Aqui está sua lista de compras!</span>
    <hr>
    </div>
    <br>

    <style>
        .row div label{
            font-size: 12px;
        }
    </style>

    <div class="container">
        <h1 class="text-warning">Suas transações!</h1>
        <p class="text-secondary">Tenha controle de todas suas transações acompanhando a lista de tudo que já comprou na Meu carrinho</p>
    
    <hr>

    <fieldset class="fieldset">
        <div>
            <table class="table table-bordered table-hover">

                <thead>
                    <tr>
                        <th  class="text-center">#</th>
                        <th>Produto</th>
                        <th>Data</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php

                    $get_p = $conexao->query("SELECT * FROM carrinho WHERE en_ip = '$codigo' AND given = 'yes'");
                    $lin_p = mysqli_num_rows($get_p);
                    while($pro = mysqli_fetch_array($get_p)){
                        $ref_p = $pro['ref'];
                        $id_p = $pro['id'];
                        $prod = $pro['produto'];
                        $quando = $pro['quando'];
                        $estado = $pro['given'];
                        $get_p_info = $conexao->query("SELECT * FROM produtos WHERE ref = '$ref_p'");

                        while($prods = mysqli_fetch_array($get_p_info)){
                    ?>
                    <tr>
                        <td class="text-center">
                        
                            <svg fill="green" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-circle" viewBox="0 0 16 16">
                            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                            <path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z"/>
                            </svg>
                        
                        </td>
                        <td>
                            <?=$prods['produto']?>
                        </td>
                        <td > <?php
                        
                        $sep = explode(" ", $quando);
                        $datas = $sep[0];
                        $horas = $sep[1];
                        $sep_datas = explode("-", $datas);
                        $mes_num = $sep_datas[1];
                        $dia = $sep_datas[2];
                        $ano = $sep_datas[0];
                        $mes = NULL;
                        $hora_all = explode(":", $horas);
                        $hora = $hora_all[0];
                       

                        switch ($mes_num) {
                            case 01:
                                $mes = "Jan";
                                break;
                            case 02:
                                $mes = "Fev";
                                break;
                            case 03:
                                $mes = "Mar";
                                break;
                            case 04:
                                $mes = "Abr";
                                break;
                            case 05:
                                $mes = "Maio";
                                break;
                            case 06:
                                $mes = "Jun";
                                break;
                            case 07:
                                $mes = "Jul";
                                break;
                            case 8:
                                $mes = "Ago";
                                break;
                            case 9:
                                $mes = "Set";
                                break;
                            case 10:
                                $mes = "Out";
                                break;
                            case 11:
                                $mes = "Nov";
                                break;
                            case 12:
                                $mes = "Dez";
                                break;
                            
                            default:
                                $mes = "Desconhecido";
                                break;
                        }

                        echo "{$dia} {$mes}, {$ano}. as {$hora}h";
                        ?></td>
                        <td   class="text-center">
                            <!-- Generated by IcoMoon.io -->
                            <svg onclick="deleteProd('<?=$id_p?>')" fill="red" style="cursor: pointer" version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
                            <title>Apagar da lista</title>
                            <path d="M4.5 22.125c-0 0.003-0 0.006-0 0.008 0 0.613 0.494 1.11 1.105 1.116h12.79c0.612-0.006 1.105-0.504 1.105-1.117 0-0.003-0-0.006-0-0.009v0-15h-15zM6 8.625h12v13.125h-12z"></path>
                            <path d="M7.875 10.125h1.5v9.375h-1.5v-9.375z"></path>
                            <path d="M11.25 10.125h1.5v9.375h-1.5v-9.375z"></path>
                            <path d="M14.625 10.125h1.5v9.375h-1.5v-9.375z"></path>
                            <path d="M15.375 4.125v-2.25c0-0.631-0.445-1.125-1.013-1.125h-4.725c-0.568 0-1.013 0.494-1.013 1.125v2.25h-5.625v1.5h18v-1.5zM10.125 2.25h3.75v1.875h-3.75z"></path>
                            </svg>
                        </td>
                    </tr>

                    <?php
                        }
                    }
                    ?>
                </tbody>

            </table>
        </div>
    </fieldset>
    </div>

    <br>
    <br>

<br><br><br>


<footer class="bg-warning py-3">
    <br>
    <div class="container">
        <div class="footer row">
            <div class="col-12 col-md-3 col-lg-3 col-sm-6 col-xl-3">
                <img src="../img/banner_p.png" height="40px" alt="">
                <br><br>
                <span class="text-danger">Luanda, Kilamba.</span>
            </div>
            <div class="col-12 col-md-3 col-lg-3 col-sm-6 col-xl-3">
                <br>
                <h5 class="text-white">Trabalhe connosco</h5>
                <a href="#" class="text-white text-decoration-none">Torne se um parceiro</a><br>
                <a href="#" class="text-white text-decoration-none">Torne se um Entregador</a><br>
                <a href="#" class="text-white text-decoration-none">Anuncios</a>
            </div>
            <div class="col-12 col-md-3 col-lg-3 col-sm-6 col-xl-3"> <br>
                <h5 class="text-white">Empresa</h5>
                <a href="#" class="text-white text-decoration-none">Sobre nós</a><br>
                <a href="#" class="text-white text-decoration-none">FAQs</a><br>
                <a href="#" class="text-white text-decoration-none">Parceiro perto de sí</a>
            </div>
            <div class="col-12 col-md-3 col-lg-3 col-sm-6 col-xl-3"> <br>
                <h5 class="text-white">Ajuda e Suporte</h5>
                <a href="tel:244946445629" class="text-white text-decoration-none">+244 946 445 629</a><br>
                <a href="#" class="text-white text-decoration-none">Contacte nos</a><br>
                <a href="#" class="text-white text-decoration-none">Anuncios</a>
            </div>
        </div><!-- Termino da parte dos conteudos do footer e dados da emoresa -->
        <br><br><br>
        <div class="foot-2 d-flex justify-content-between">
            <div class="copyright font-lighter text-white">2022 Meu Carrinho, Ltda &middot; <a href="#" class="text-decoration-none text-white " style="text-decoration: underline ;">Termos e codições</a></div>
            <div class="mideas gap-2 d-flex">
                <svg fill="white" height="1.5em" width="1.5em" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><path d="M279.14 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.43 0 225.36 0c-73.22 0-121.08 44.38-121.08 124.72v70.62H22.89V288h81.39v224h100.17V288z"/></svg>
               
                <svg fill="white" height="1.5em" width="1.5em" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z"/></svg>
    
                <svg fill="white" height="1.5em" width="1.5em" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path d="M100.28 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.58 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.28 61.9 111.28 142.3V448z"/></svg>
    
            </div>
        </div>
    </div>
    <br>
</footer>


<!--Area do icone de chat bot para conversas no whatsapp-->

    <div style="right: 1rem; bottom: 2rem; position: fixed" class="bg-danger p-2 fixo">
        <!-- Generated by IcoMoon.io -->
        <svg fill="white" version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
        <title>chat-bubble</title>
        <path d="M21.010 18.399c1.431-1.275 2.24-2.974 2.24-4.738 0-1.874-0.877-3.627-2.471-4.936-1.55-1.274-3.603-1.975-5.779-1.975s-4.229 0.701-5.779 1.975c-1.593 1.309-2.471 3.062-2.471 4.936s0.877 3.627 2.471 4.936c1.55 1.273 3.603 1.975 5.779 1.975 0.29 0 0.582-0.013 0.871-0.038l0.494 0.428c1.634 1.422 3.783 2.288 6.134 2.288h0.75v-1.596l-0.22-0.22c-0.844-0.847-1.527-1.855-1.998-2.974l-0.023-0.061zM17.348 19.828l-0.992-0.86-0.331 0.041c-0.308 0.040-0.664 0.062-1.025 0.062h-0c-3.722 0-6.75-2.427-6.75-5.411s3.028-5.411 6.75-5.411 6.75 2.427 6.75 5.411c0 1.486-0.742 2.874-2.088 3.907l-0.432 0.331 0.199 0.564c0.439 1.219 1.040 2.272 1.792 3.199l-0.016-0.020c-1.493-0.255-2.805-0.899-3.867-1.823l0.010 0.008z"></path>
        <path d="M2.821 14.882c0.672-0.845 1.225-1.823 1.609-2.882l0.023-0.072 0.198-0.561-0.432-0.331c-1.27-0.974-1.969-2.282-1.969-3.682 0-2.814 2.86-5.103 6.375-5.103 2.586 0 4.817 1.239 5.816 3.014 0.185-0.009 0.372-0.014 0.559-0.014q0.564 0 1.117 0.055c-0.386-1-1.056-1.913-1.978-2.67-1.48-1.215-3.438-1.885-5.514-1.885s-4.035 0.669-5.514 1.885c-1.522 1.251-2.361 2.926-2.361 4.718 0 1.678 0.766 3.295 2.121 4.511-0.467 1.107-1.109 2.052-1.902 2.847l-0.219 0.219v1.57h0.75c1.456-0 2.831-0.349 4.046-0.967l-0.051 0.023c-0.128-0.466-0.213-1.006-0.237-1.562l-0.001-0.015c-0.702 0.419-1.519 0.733-2.39 0.895l-0.046 0.007z"></path>
        </svg>
    
    </div>

    <script>
        $("#open_menu").click(function(){
            $(".the_menu").fadeToggle("fast");
            $(this).toggleClass("bg-white rounded-2 text-danger");
        });

        $('.pubs').owlCarousel({
    loop:false,
    margin:60,
    autoWidth:false,
    indicators:false,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
            nav:false
        },
        600:{
            items:2,
            nav:false
        },
        1000:{
            items:3,
            nav:false,
            loop:false
        },
        1300:{
            items:4,
            nav:false,
            loop:false
        }
    }
});

$('.lojas').owlCarousel({
    loop:false,
    margin:90,
    autoWidth:false,
    indicators:false,
    responsiveClass:true,
    responsive:{
        0:{
            items:1,
            nav:false
        },
        600:{
            items:2,
            nav:false
        },
        1000:{
            items:2,
            nav:false,
            loop:false
        },
        1300:{
            items:3,
            nav:false,
            loop:false
        }
    }
});


$("#compras").click(function (){
    window.location.href = "compras_all.php";
})


function deleteProd(params) {
    var form_data = {
        typeID: params,
    }
     $.post('./func_f/delete_prod.php', form_data, function(resp) {
                
                Swal.fire(
                    'Alterado',
                    "Produto " + resp + " da sua lista " ,
                    'success'
                ); // <-- display response from the PHP script, if any
            }
        );
}
    </script>
</body>
</html>